name: Dynamic Env Example

on:
  workflow_dispatch:

jobs:
  dynamic-env-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Set MY_DYNAMIC
        run: |
          echo "TODAY=$(date)" >> $GITHUB_ENV

      - name: Step 2 - show current time
        run: echo "TODAY is = $TODAY"

      - name: Step 3 - show current time again
        run: echo "Step 3 sees "TODAY is = $TODAY"
