name: Static Env Example
#this is for testing static env vars in a workflow
#this workflow will run when manually triggered   
on:
  workflow_dispatch:

jobs:
  static-env-demo:
    runs-on: ubuntu-latest
    env:
      MY_STATIC: HelloFromStaticEnv
    steps:
      - name: Step 1 - Show MY_STATIC
        run: echo "Step 1 sees = $MY_STATIC"

      - name: Step 2 - Show MY_STATIC again
        run: echo "Step 2 sees = $MY_STATIC"
