name: Dynamic Env Example

on: push
  

jobs:
  dynamic-env-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Set MY_DYNAMIC
        run: |
          echo "TODAY=$(date)" >> $GITHUB_ENV

      - name: Step 2 - show current time
        run: echo "TODAY is = $TODAY"
        
      - name: Wait for 20 seconds
        run: sleep 20
        
      - name: Step 3 - show current time again
        run: echo Step 3 sees "TODAY is = $TODAY"
